config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'
  devise_for :users
  resources :contacts, only: %i[index]
  resources :contact_files, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/insertable.rb
module Insertable
  extend ActiveSupport::Concern
  class_methods do
    def add_timestamp(record)
      time = Time.now.utc
      record['created_at'] = time
      record['updated_at'] = time
    end

    def insert_all_normalized(records, options = { returning: [:id] })
      normalized = normalize(records)
      result = nil
      begin
        result = insert_all(normalized, options)
      rescue ActiveRecord::StatementInvalid => e
        result = e
      end
      result
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  include Insertable

  REGULAR_EXPRESSION_MASK_CREDIT_CARD = /.(?=....)/.freeze
  CREDIT_CARD_FRANCHISES = %i[
    amex
    diners
    discover
    jcb
    mastercard
    visa
  ].freeze

  # Relations
  belongs_to :user

  # Enums
  enum franchise: CREDIT_CARD_FRANCHISES

  # Callbacks
  before_create :mask_card_number

  def mask_card_number
    self.credit_card = credit_card&.gsub(REGULAR_EXPRESSION_MASK_CREDIT_CARD, '*')
  end

  def self.normalize(records)
    records.each do |rec|
      add_timestamp(rec)
      rec[:credit_card] = rec[:credit_card]&.gsub(REGULAR_EXPRESSION_MASK_CREDIT_CARD, '*')
    end
  end
end

app/models/contact_file.rb
class ContactFile < ApplicationRecord
  # Relations
  belongs_to :user
  has_many :file_columns, dependent: :destroy
  has_one_attached :file
  accepts_nested_attributes_for :file_columns

  # Enum
  enum status: %i[on_hold processing failed terminated]

  # Callbacks
  after_create :enqueue_importation

  # Serializers
  serialize :row_errors, Array
  before_validation :validate_file_columns

  def badge
    return 'primary' if on_hold?
    return 'info' if processing?
    return 'danger' if failed?
    return 'success' if terminated?
  end

  # Callbacks

  def enqueue_importation
    ImportContactsJob.perform_later(id)
  end

  def validate_file_columns
    return if file_columns.map(&:field).map(&:to_sym).sort == FileColumn::FIELDS.sort

    errors.add(:base, 'Invalid fields')
  end
end

app/models/file_column.rb
class FileColumn < ApplicationRecord
  FIELDS = %i[
    name
    birthday
    phone
    address
    credit_card
    email
  ].freeze

  # Relations
  belongs_to :contact_file

  # Enums
  enum field: FIELDS, _suffix: :field

  # Validations
  validates_presence_of :column_name, :field
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Relations
  has_many :contacts
  has_many :contact_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contact_files = pagy(current_user.contact_files.with_attached_file)
  end

  def new
    @contact_file = ContactFile.new
    @contact_file.file_columns.build
  end

  def create
    @contact_file = current_user.contact_files.new(contact_file_params)

    respond_to do |format|
      if @contact_file.save
        format.html { redirect_to contact_files_path, notice: 'File saved successfully.' }
      else
        format.html { redirect_to contact_files_path, notice: @contact_file.errors.full_messages.join(' ') }
      end
    end
  end

  private

  def contact_file_params
    params.require(:contact_file).permit(:file, file_columns_attributes: %i[column_name field])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contacts = pagy(current_user.contacts)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/contact_file_helper.rb
module ContactFileHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/file_columns_helper.rb
module FileColumnsHelper
  def fields_for_select
    FileColumn.fields.keys.map do |file_column_key|
      [file_column_key.humanize, file_column_key]
    end
  end
end

app/views/contact_files/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-xl-12">
        <h2 class="text-center">Uploaded Files</h2>
      </div>
    </div>
    <br>
    <div class="row text-center">
      <div class="col-xl-12">
        <%= link_to 'Import CSV File', new_contact_file_path, class: "btn btn-success" %>
        <%= link_to 'Contacts', contacts_path, class: "btn btn-primary" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-xl-12">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">File name</th>
              <th scope="col">Status</th>
              <th scope="col">Errors</th>
            </tr>
          </thead>
          <tbody>
            <% @contact_files.each_with_index do |contact_file, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td>
                <%= link_to contact_file.file.filename, rails_blob_path(contact_file.file, disposition: 'attachment') %>
              </td>
              <td>
                <span class="badge bg-<%= contact_file.badge %>"><%= contact_file.status %></span>
              </td>
              <td>
                <ol class="list-group list-group-numbered">
                  <% contact_file.row_errors.each do |row_error| %>
                  <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                      <div class="fw-bold">Row: <%= row_error[:row] %></div>
                      <% row_error[:errors].each do |error_key| %>
                        <%= t("contact_file_errors.#{error_key}") %> <br>
                      <% end %>
                    </div>
                  </li>
                  <% end %>
                </ol>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= render 'partials/pagination' %>
      </div>
    </div>
  </div>
</div>

app/views/contact_files/new.html.erb
<h2 class="text-center">Import Contacts</h2>
<br>
<%= form_with(model: @contact_file, local: true) do |f| %>
  <div class="row">
    <%= f.fields_for :file_columns do |file_column_subform| %>
      <% (1..6).each do |number| %>
        <div class="col-xl-6 mb-3">
          <%= file_column_subform.text_field :column_name, class: 'form-control', required: true, name: "contact_file[file_columns_attributes][#{number}][column_name]" %>
        </div>
        <div class="col-xl-6 mb-3">
          <%= file_column_subform.select(:field, fields_for_select, { include_blank: 'Select option' }, class: "form-control", required: true, name: "contact_file[file_columns_attributes][#{number}][field]") %>
        </div>
      <% end %>
    <% end %>
  </div>
  <br>
  <div class="row">
    <div class="col-xl-12 mb-3">
      <label for="formFile" class="form-label">Select csv file</label>
      <%= f.file_field :file, class: 'form-control', accept: '.csv' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xl-12 text-center">
      <button type="submit" class="text-center btn btn-primary">Submit</button>
      <%= link_to 'Go back', contact_files_path, class: 'text-center btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/contacts/bulk_import.html.erb
<h2 class="text-center">Import Contacts</h2>
<br>

<%= form_with url: import_contacts_path do |f| %>
  <div class="row">
    <div class="col-xl-12 mb-3">
      <label for="formFile" class="form-label">Select csv file</label>
      <%= f.file_field :file, class: 'form-control', accept: '.csv' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xl-12 text-center">
      <button type="submit" class="text-center btn btn-primary">Submit</button>
    </div>
  </div>
<% end %>

app/views/contacts/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-xl-12">
        <h2 class="text-center">Contacts</h2>
      </div>
    </div>
    <br>
    <div class="row text-center">
      <div class="col-xl-12">
        <%= link_to 'Import CSV File', new_contact_file_path, class: "btn btn-success" %>
        <%= link_to 'Uploaded Files', contact_files_path, class: "btn btn-primary" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-xl-12">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Birthday</th>
              <th scope="col">Phone</th>
              <th scope="col">Address</th>
              <th scope="col">Credit Card</th>
              <th scope="col">Franchise</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
            <% @contacts.each_with_index do |contact, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= contact.name %></td>
              <td><%= contact.birthday&.strftime("%Y %B %d") %></td>
              <td><%= contact.phone %></td>
              <td><%= contact.address %></td>
              <td><%= contact.credit_card %></td>
              <td><%= contact.franchise&.humanize %></td>
              <td><%= contact.email %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= render 'partials/pagination' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-light bg-light">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      </nav>
    <% end %>
    <p class="text-center notice"><%= notice %></p>
    <p class="text-center alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_pagination.html.erb
<div class="d-flex justify-content-center mt-4">
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
</div>